### ISSUE TITLE
动画的执行时间有个小小bug，设置执行动画时间duration，被写死了，望采纳。

### ISSUE THREAD

**Issue by GoldL** [stoneWeb/react-native-parabolic#1]
作者您好，真的非常感谢您的这个控件。但是这个控件有个小小的bug，就是设置执行动画时间duration，被写死了，无法改变执行动画时间duration。
Animated.timing(this.state.runAnim, {
         toValue: inputRange.length,
         duration: 350
     }).start(() => { this.props.animateEnd(data) })
望采纳。谢谢！（小白第一次评论，语言表达不好，请见谅）

**Comment by stoneWeb** [comment]
多些提醒，马上改正！
