### ISSUE TITLE
chore(npm): 你需要重新发布 npm 包

### ISSUE THREAD

**Issue by geminiyellow** [stoneWeb/react-native-parabolic#5]
拿下来之后仍然是 1.1.1

![image](https://user-images.githubusercontent.com/929878/44708652-a60cfd00-aae2-11e8-87e5-7d0933f6596e.png)

**Comment by geminiyellow** [comment]
@khoerling hey sir, please republish your npm package, it still 1.1.1 now.

**Comment by khoerling** [comment]
@geminiyellow yo!  thank you for the reminder:  https://github.com/khoerling/react-native-parabolic

**Comment by geminiyellow** [comment]
opps, @khoerling why not use this repo and need create a new fork?

**Comment by geminiyellow** [comment]
@stoneWeb @khoerling so, i have to install from github and there is not new npm release, right ?

**Comment by stoneWeb** [comment]
Has been republished.
